// SPDX-FileCopyrightText: 2024 Mass Labs
//
// SPDX-License-Identifier: MIT

// Code generated by "stringer -output gen_tickType_string.go -trimprefix tt -type tickType ."; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ttInvalid-0]
	_ = x[ttWait-1]
	_ = x[ttOp-2]
	_ = x[ttOpInternal-3]
	_ = x[ttDebounceSessions-4]
	_ = x[ttPaymentWatcher-5]
	_ = x[ttMemoryStats-6]
	_ = x[ttTickStats-7]
}

const _tickType_name = "InvalidWaitOpOpInternalDebounceSessionsPaymentWatcherMemoryStatsTickStats"

var _tickType_index = [...]uint8{0, 7, 11, 13, 23, 39, 53, 64, 73}

func (i tickType) String() string {
	if i >= tickType(len(_tickType_index)-1) {
		return "tickType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tickType_name[_tickType_index[i]:_tickType_index[i+1]]
}
