// Generated from /nix/store/f85zzi4ixccx8nanqqimici7k99a90vi-source/network-schema/base_types.proto at version v3 (8c69c384bab94dce187894ddce82451fcb0956b2)

// SPDX-FileCopyrightText: 2024 Mass Labs
//
// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: base_types.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wether a listing sould be published or not
type ListingViewState int32

const (
	ListingViewState_LISTING_VIEW_STATE_UNSPECIFIED ListingViewState = 0
	ListingViewState_LISTING_VIEW_STATE_PUBLISHED   ListingViewState = 1
	ListingViewState_LISTING_VIEW_STATE_DELETED     ListingViewState = 2
)

// Enum value maps for ListingViewState.
var (
	ListingViewState_name = map[int32]string{
		0: "LISTING_VIEW_STATE_UNSPECIFIED",
		1: "LISTING_VIEW_STATE_PUBLISHED",
		2: "LISTING_VIEW_STATE_DELETED",
	}
	ListingViewState_value = map[string]int32{
		"LISTING_VIEW_STATE_UNSPECIFIED": 0,
		"LISTING_VIEW_STATE_PUBLISHED":   1,
		"LISTING_VIEW_STATE_DELETED":     2,
	}
)

func (x ListingViewState) Enum() *ListingViewState {
	p := new(ListingViewState)
	*p = x
	return p
}

func (x ListingViewState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListingViewState) Descriptor() protoreflect.EnumDescriptor {
	return file_base_types_proto_enumTypes[0].Descriptor()
}

func (ListingViewState) Type() protoreflect.EnumType {
	return &file_base_types_proto_enumTypes[0]
}

func (x ListingViewState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListingViewState.Descriptor instead.
func (ListingViewState) EnumDescriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{0}
}

type RequestId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sender chooses a unique number per request that must not
	// conflict with requests the other party sends.
	// one suggestion would be each party keeps a counter per sessions.
	// responses use the negative request number.
	Raw int64 `protobuf:"zigzag64,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *RequestId) Reset() {
	*x = RequestId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestId) ProtoMessage() {}

func (x *RequestId) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestId.ProtoReflect.Descriptor instead.
func (*RequestId) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{0}
}

func (x *RequestId) GetRaw() int64 {
	if x != nil {
		return x.Raw
	}
	return 0
}

type ObjectId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// at least 8 bytes. used to references updates to their objects.
	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *ObjectId) Reset() {
	*x = ObjectId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectId) ProtoMessage() {}

func (x *ObjectId) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectId.ProtoReflect.Descriptor instead.
func (*ObjectId) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectId) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *Signature) Reset() {
	*x = Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{2}
}

func (x *Signature) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type PublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{3}
}

func (x *PublicKey) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type Hash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *Hash) Reset() {
	*x = Hash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash.ProtoReflect.Descriptor instead.
func (*Hash) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{4}
}

func (x *Hash) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type EthereumAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *EthereumAddress) Reset() {
	*x = EthereumAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthereumAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthereumAddress) ProtoMessage() {}

func (x *EthereumAddress) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthereumAddress.ProtoReflect.Descriptor instead.
func (*EthereumAddress) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{5}
}

func (x *EthereumAddress) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type IPFSAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *IPFSAddress) Reset() {
	*x = IPFSAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPFSAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPFSAddress) ProtoMessage() {}

func (x *IPFSAddress) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPFSAddress.ProtoReflect.Descriptor instead.
func (*IPFSAddress) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{6}
}

func (x *IPFSAddress) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type Uint256 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *Uint256) Reset() {
	*x = Uint256{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint256) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint256) ProtoMessage() {}

func (x *Uint256) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint256.ProtoReflect.Descriptor instead.
func (*Uint256) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{7}
}

func (x *Uint256) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type ShopCurrency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId uint64 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Contract address for an ERC20 token.
	// 20 zero bytes for native chain currency, like ETH.
	Address *EthereumAddress `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ShopCurrency) Reset() {
	*x = ShopCurrency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopCurrency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCurrency) ProtoMessage() {}

func (x *ShopCurrency) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCurrency.ProtoReflect.Descriptor instead.
func (*ShopCurrency) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{8}
}

func (x *ShopCurrency) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ShopCurrency) GetAddress() *EthereumAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type Payee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// user handle, like "escrow" or "direct", used during checkout
	Name    string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address *EthereumAddress `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ChainId uint64           `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// controls how the payment is reaches the payee.
	// true:  forwarded via pay() method
	// false: normal transfer
	// See also:
	// https://github.com/masslbs/contracts/
	// commit: 377aba24796e029945696350db581ec1f65da657
	// file: src/IPayments.sol#L90-L95.
	CallAsContract bool `protobuf:"varint,4,opt,name=call_as_contract,json=callAsContract,proto3" json:"call_as_contract,omitempty"`
}

func (x *Payee) Reset() {
	*x = Payee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payee) ProtoMessage() {}

func (x *Payee) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payee.ProtoReflect.Descriptor instead.
func (*Payee) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{9}
}

func (x *Payee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Payee) GetAddress() *EthereumAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Payee) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Payee) GetCallAsContract() bool {
	if x != nil {
		return x.CallAsContract
	}
	return false
}

type ShippingRegion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// user-focused identifier for the region
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the location
	//
	// the region for an order is picked by successivly matching fields.
	// empty-string values match everything / act as catch-all's.
	//
	// therefore this can be used to say "only on this city" for pickups.
	// Or, for an international region, all three fields should be empty.
	//
	// TODO: need a country map and dropdowns for matching to work
	Country             string                `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode          string                `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	City                string                `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	OrderPriceModifiers []*OrderPriceModifier `protobuf:"bytes,5,rep,name=order_price_modifiers,json=orderPriceModifiers,proto3" json:"order_price_modifiers,omitempty"`
}

func (x *ShippingRegion) Reset() {
	*x = ShippingRegion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShippingRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingRegion) ProtoMessage() {}

func (x *ShippingRegion) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingRegion.ProtoReflect.Descriptor instead.
func (*ShippingRegion) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{10}
}

func (x *ShippingRegion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShippingRegion) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ShippingRegion) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *ShippingRegion) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ShippingRegion) GetOrderPriceModifiers() []*OrderPriceModifier {
	if x != nil {
		return x.OrderPriceModifiers
	}
	return nil
}

type OrderPriceModifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the title of the option (like VAT Tax, Premium Shipping.)
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Types that are assignable to Modification:
	//
	//	*OrderPriceModifier_Percentage
	//	*OrderPriceModifier_Absolute
	Modification isOrderPriceModifier_Modification `protobuf_oneof:"modification"`
}

func (x *OrderPriceModifier) Reset() {
	*x = OrderPriceModifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPriceModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPriceModifier) ProtoMessage() {}

func (x *OrderPriceModifier) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPriceModifier.ProtoReflect.Descriptor instead.
func (*OrderPriceModifier) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{11}
}

func (x *OrderPriceModifier) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (m *OrderPriceModifier) GetModification() isOrderPriceModifier_Modification {
	if m != nil {
		return m.Modification
	}
	return nil
}

func (x *OrderPriceModifier) GetPercentage() *Uint256 {
	if x, ok := x.GetModification().(*OrderPriceModifier_Percentage); ok {
		return x.Percentage
	}
	return nil
}

func (x *OrderPriceModifier) GetAbsolute() *PlusMinus {
	if x, ok := x.GetModification().(*OrderPriceModifier_Absolute); ok {
		return x.Absolute
	}
	return nil
}

type isOrderPriceModifier_Modification interface {
	isOrderPriceModifier_Modification()
}

type OrderPriceModifier_Percentage struct {
	// this is multiplied with the sub-total before being divided by 100.
	Percentage *Uint256 `protobuf:"bytes,2,opt,name=percentage,proto3,oneof"`
}

type OrderPriceModifier_Absolute struct {
	Absolute *PlusMinus `protobuf:"bytes,3,opt,name=absolute,proto3,oneof"`
}

func (*OrderPriceModifier_Percentage) isOrderPriceModifier_Modification() {}

func (*OrderPriceModifier_Absolute) isOrderPriceModifier_Modification() {}

// + or - some value
type PlusMinus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlusSign bool     `protobuf:"varint,1,opt,name=plus_sign,json=plusSign,proto3" json:"plus_sign,omitempty"` // true for + / false for -
	Diff     *Uint256 `protobuf:"bytes,2,opt,name=diff,proto3" json:"diff,omitempty"`
}

func (x *PlusMinus) Reset() {
	*x = PlusMinus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlusMinus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlusMinus) ProtoMessage() {}

func (x *PlusMinus) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlusMinus.ProtoReflect.Descriptor instead.
func (*PlusMinus) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{12}
}

func (x *PlusMinus) GetPlusSign() bool {
	if x != nil {
		return x.PlusSign
	}
	return false
}

func (x *PlusMinus) GetDiff() *Uint256 {
	if x != nil {
		return x.Diff
	}
	return nil
}

type ListingMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Images      []string `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *ListingMetadata) Reset() {
	*x = ListingMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingMetadata) ProtoMessage() {}

func (x *ListingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingMetadata.ProtoReflect.Descriptor instead.
func (*ListingMetadata) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{13}
}

func (x *ListingMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListingMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListingMetadata) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type ListingOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ObjectId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the title of the option (like Color, Size, etc.)
	Title      string              `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Variations []*ListingVariation `protobuf:"bytes,3,rep,name=variations,proto3" json:"variations,omitempty"`
}

func (x *ListingOption) Reset() {
	*x = ListingOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingOption) ProtoMessage() {}

func (x *ListingOption) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingOption.ProtoReflect.Descriptor instead.
func (*ListingOption) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{14}
}

func (x *ListingOption) GetId() *ObjectId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListingOption) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListingOption) GetVariations() []*ListingVariation {
	if x != nil {
		return x.Variations
	}
	return nil
}

type ListingVariation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ObjectId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // needs to be unique per listing
	// the metadata of the variation: for example if the option is Color
	// then the title might be "Red"
	VariationInfo *ListingMetadata `protobuf:"bytes,2,opt,name=variation_info,json=variationInfo,proto3" json:"variation_info,omitempty"`
	// this alters the price
	Diff *PlusMinus `protobuf:"bytes,3,opt,name=diff,proto3" json:"diff,omitempty"`
}

func (x *ListingVariation) Reset() {
	*x = ListingVariation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingVariation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingVariation) ProtoMessage() {}

func (x *ListingVariation) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingVariation.ProtoReflect.Descriptor instead.
func (*ListingVariation) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{15}
}

func (x *ListingVariation) GetId() *ObjectId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListingVariation) GetVariationInfo() *ListingMetadata {
	if x != nil {
		return x.VariationInfo
	}
	return nil
}

func (x *ListingVariation) GetDiff() *PlusMinus {
	if x != nil {
		return x.Diff
	}
	return nil
}

// used to signal general availability, not the concrete numbers
// See ChangeStock for that
type ListingStockStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// each variation must belong to a different option
	VariationIds []*ObjectId `protobuf:"bytes,1,rep,name=variation_ids,json=variationIds,proto3" json:"variation_ids,omitempty"`
	// Types that are assignable to Status:
	//
	//	*ListingStockStatus_InStock
	//	*ListingStockStatus_ExpectedInStockBy
	Status isListingStockStatus_Status `protobuf_oneof:"status"`
}

func (x *ListingStockStatus) Reset() {
	*x = ListingStockStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListingStockStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingStockStatus) ProtoMessage() {}

func (x *ListingStockStatus) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingStockStatus.ProtoReflect.Descriptor instead.
func (*ListingStockStatus) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{16}
}

func (x *ListingStockStatus) GetVariationIds() []*ObjectId {
	if x != nil {
		return x.VariationIds
	}
	return nil
}

func (m *ListingStockStatus) GetStatus() isListingStockStatus_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (x *ListingStockStatus) GetInStock() bool {
	if x, ok := x.GetStatus().(*ListingStockStatus_InStock); ok {
		return x.InStock
	}
	return false
}

func (x *ListingStockStatus) GetExpectedInStockBy() *timestamppb.Timestamp {
	if x, ok := x.GetStatus().(*ListingStockStatus_ExpectedInStockBy); ok {
		return x.ExpectedInStockBy
	}
	return nil
}

type isListingStockStatus_Status interface {
	isListingStockStatus_Status()
}

type ListingStockStatus_InStock struct {
	InStock bool `protobuf:"varint,2,opt,name=in_stock,json=inStock,proto3,oneof"`
}

type ListingStockStatus_ExpectedInStockBy struct {
	ExpectedInStockBy *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expected_in_stock_by,json=expectedInStockBy,proto3,oneof"`
}

func (*ListingStockStatus_InStock) isListingStockStatus_Status() {}

func (*ListingStockStatus_ExpectedInStockBy) isListingStockStatus_Status() {}

// order related messages
type AddressDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address1     string  `protobuf:"bytes,2,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2     string  `protobuf:"bytes,3,opt,name=address2,proto3" json:"address2,omitempty"`
	City         string  `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode   string  `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country      string  `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	EmailAddress string  `protobuf:"bytes,7,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	PhoneNumber  *string `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
}

func (x *AddressDetails) Reset() {
	*x = AddressDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressDetails) ProtoMessage() {}

func (x *AddressDetails) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressDetails.ProtoReflect.Descriptor instead.
func (*AddressDetails) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{17}
}

func (x *AddressDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddressDetails) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *AddressDetails) GetAddress2() string {
	if x != nil {
		return x.Address2
	}
	return ""
}

func (x *AddressDetails) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressDetails) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *AddressDetails) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AddressDetails) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *AddressDetails) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

// Created by the relay after an order has been commited.
// It signals that an order is needs to be payed.
type PaymentDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// for verification. Compare against getPaymentId(PaymentReq)
	PaymentId *Hash `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// start of PaymentRequest data
	// (rest can be determained by other order fields)
	Total *Uint256 `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	// content-addressable hashes of the listing(s) being purchased
	ListingHashes []*IPFSAddress `protobuf:"bytes,3,rep,name=listing_hashes,json=listingHashes,proto3" json:"listing_hashes,omitempty"`
	// PaymentRequest fields that are not obvious to the caller
	Ttl            string          `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	ShopSignature  *Signature      `protobuf:"bytes,5,opt,name=shop_signature,json=shopSignature,proto3" json:"shop_signature,omitempty"` // end of PaymentRequest data
	ShippingRegion *ShippingRegion `protobuf:"bytes,6,opt,name=shipping_region,json=shippingRegion,proto3" json:"shipping_region,omitempty"`
}

func (x *PaymentDetails) Reset() {
	*x = PaymentDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDetails) ProtoMessage() {}

func (x *PaymentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDetails.ProtoReflect.Descriptor instead.
func (*PaymentDetails) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{18}
}

func (x *PaymentDetails) GetPaymentId() *Hash {
	if x != nil {
		return x.PaymentId
	}
	return nil
}

func (x *PaymentDetails) GetTotal() *Uint256 {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *PaymentDetails) GetListingHashes() []*IPFSAddress {
	if x != nil {
		return x.ListingHashes
	}
	return nil
}

func (x *PaymentDetails) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *PaymentDetails) GetShopSignature() *Signature {
	if x != nil {
		return x.ShopSignature
	}
	return nil
}

func (x *PaymentDetails) GetShippingRegion() *ShippingRegion {
	if x != nil {
		return x.ShippingRegion
	}
	return nil
}

// generate by the relay to notify that the oder has been paid for
type OrderTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// might not have a tx hash in case of an internal transaction
	TxHash    *Hash `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockHash *Hash `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
}

func (x *OrderTransaction) Reset() {
	*x = OrderTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTransaction) ProtoMessage() {}

func (x *OrderTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTransaction.ProtoReflect.Descriptor instead.
func (*OrderTransaction) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{19}
}

func (x *OrderTransaction) GetTxHash() *Hash {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *OrderTransaction) GetBlockHash() *Hash {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

// OrderedItems is used to add items to or remove items from an order.
type OrderedItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListingId    *ObjectId   `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	VariationIds []*ObjectId `protobuf:"bytes,2,rep,name=variation_ids,json=variationIds,proto3" json:"variation_ids,omitempty"`
	Quantity     uint32      `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *OrderedItem) Reset() {
	*x = OrderedItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_types_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderedItem) ProtoMessage() {}

func (x *OrderedItem) ProtoReflect() protoreflect.Message {
	mi := &file_base_types_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderedItem.ProtoReflect.Descriptor instead.
func (*OrderedItem) Descriptor() ([]byte, []int) {
	return file_base_types_proto_rawDescGZIP(), []int{20}
}

func (x *OrderedItem) GetListingId() *ObjectId {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *OrderedItem) GetVariationIds() []*ObjectId {
	if x != nil {
		return x.VariationIds
	}
	return nil
}

func (x *OrderedItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_base_types_proto protoreflect.FileDescriptor

var file_base_types_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x1d, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x12, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22,
	0x1c, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x1d, 0x0a,
	0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61,
	0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x1d, 0x0a, 0x09,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x18, 0x0a, 0x04, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x23, 0x0a, 0x0f, 0x45, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75,
	0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x1f, 0x0a, 0x0b, 0x49, 0x50,
	0x46, 0x53, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x07, 0x55,
	0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x61, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x70,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61,
	0x73, 0x73, 0x2e, 0x45, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x05,
	0x50, 0x61, 0x79, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x45, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75,
	0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10,
	0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x61, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x63, 0x61, 0x6c, 0x6c, 0x41, 0x73, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22, 0xc8, 0x01, 0x0a, 0x0e, 0x53, 0x68, 0x69, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x61,
	0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f,
	0x73, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x53, 0x0a, 0x15,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x13, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x73, 0x22, 0xa8, 0x01, 0x0a, 0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x36,
	0x0a, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73,
	0x2e, 0x55, 0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x61, 0x62, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x73, 0x4d, 0x69, 0x6e, 0x75, 0x73,
	0x48, 0x00, 0x52, 0x08, 0x61, 0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x42, 0x0e, 0x0a, 0x0c,
	0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x52, 0x0a, 0x09,
	0x50, 0x6c, 0x75, 0x73, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x75,
	0x73, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x6c,
	0x75, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x69, 0x66, 0x66, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61,
	0x73, 0x73, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x52, 0x04, 0x64, 0x69, 0x66, 0x66,
	0x22, 0x61, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e,
	0x6d, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0xaa, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x43, 0x0a,
	0x0e, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d,
	0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x0d, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x69, 0x66, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x50,
	0x6c, 0x75, 0x73, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x52, 0x04, 0x64, 0x69, 0x66, 0x66, 0x22, 0xc6,
	0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a, 0x0d, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x52, 0x0c, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x73, 0x12, 0x1b, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x4d,
	0x0a, 0x14, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x5f, 0x62, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x11, 0x65, 0x78, 0x70, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x42, 0x08, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x89, 0x02, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f,
	0x73, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x0c, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x88,
	0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0xc6, 0x02, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x09, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x32, 0x35, 0x36, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3f, 0x0a, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x49, 0x50, 0x46, 0x53, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x48,
	0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x3d, 0x0a, 0x0e, 0x73, 0x68, 0x6f, 0x70, 0x5f,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0d, 0x73, 0x68, 0x6f, 0x70, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x53, 0x68,
	0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x73, 0x68,
	0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x70, 0x0a, 0x10,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2a, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x30, 0x0a, 0x0a,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x48,
	0x61, 0x73, 0x68, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x22, 0x9b,
	0x01, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x34,
	0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x0d, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x52, 0x0c, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2a, 0x78, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x69, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x22, 0x0a, 0x1e, 0x4c, 0x49, 0x53, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x56, 0x49, 0x45, 0x57,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x4c, 0x49, 0x53, 0x54, 0x49, 0x4e, 0x47, 0x5f,
	0x56, 0x49, 0x45, 0x57, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x55, 0x42, 0x4c, 0x49,
	0x53, 0x48, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x4c, 0x49, 0x53, 0x54, 0x49, 0x4e,
	0x47, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x45, 0x4c,
	0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_base_types_proto_rawDescOnce sync.Once
	file_base_types_proto_rawDescData = file_base_types_proto_rawDesc
)

func file_base_types_proto_rawDescGZIP() []byte {
	file_base_types_proto_rawDescOnce.Do(func() {
		file_base_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_types_proto_rawDescData)
	})
	return file_base_types_proto_rawDescData
}

var file_base_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_base_types_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_base_types_proto_goTypes = []interface{}{
	(ListingViewState)(0),         // 0: market.mass.ListingViewState
	(*RequestId)(nil),             // 1: market.mass.RequestId
	(*ObjectId)(nil),              // 2: market.mass.ObjectId
	(*Signature)(nil),             // 3: market.mass.Signature
	(*PublicKey)(nil),             // 4: market.mass.PublicKey
	(*Hash)(nil),                  // 5: market.mass.Hash
	(*EthereumAddress)(nil),       // 6: market.mass.EthereumAddress
	(*IPFSAddress)(nil),           // 7: market.mass.IPFSAddress
	(*Uint256)(nil),               // 8: market.mass.Uint256
	(*ShopCurrency)(nil),          // 9: market.mass.ShopCurrency
	(*Payee)(nil),                 // 10: market.mass.Payee
	(*ShippingRegion)(nil),        // 11: market.mass.ShippingRegion
	(*OrderPriceModifier)(nil),    // 12: market.mass.OrderPriceModifier
	(*PlusMinus)(nil),             // 13: market.mass.PlusMinus
	(*ListingMetadata)(nil),       // 14: market.mass.ListingMetadata
	(*ListingOption)(nil),         // 15: market.mass.ListingOption
	(*ListingVariation)(nil),      // 16: market.mass.ListingVariation
	(*ListingStockStatus)(nil),    // 17: market.mass.ListingStockStatus
	(*AddressDetails)(nil),        // 18: market.mass.AddressDetails
	(*PaymentDetails)(nil),        // 19: market.mass.PaymentDetails
	(*OrderTransaction)(nil),      // 20: market.mass.OrderTransaction
	(*OrderedItem)(nil),           // 21: market.mass.OrderedItem
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_base_types_proto_depIdxs = []int32{
	6,  // 0: market.mass.ShopCurrency.address:type_name -> market.mass.EthereumAddress
	6,  // 1: market.mass.Payee.address:type_name -> market.mass.EthereumAddress
	12, // 2: market.mass.ShippingRegion.order_price_modifiers:type_name -> market.mass.OrderPriceModifier
	8,  // 3: market.mass.OrderPriceModifier.percentage:type_name -> market.mass.Uint256
	13, // 4: market.mass.OrderPriceModifier.absolute:type_name -> market.mass.PlusMinus
	8,  // 5: market.mass.PlusMinus.diff:type_name -> market.mass.Uint256
	2,  // 6: market.mass.ListingOption.id:type_name -> market.mass.ObjectId
	16, // 7: market.mass.ListingOption.variations:type_name -> market.mass.ListingVariation
	2,  // 8: market.mass.ListingVariation.id:type_name -> market.mass.ObjectId
	14, // 9: market.mass.ListingVariation.variation_info:type_name -> market.mass.ListingMetadata
	13, // 10: market.mass.ListingVariation.diff:type_name -> market.mass.PlusMinus
	2,  // 11: market.mass.ListingStockStatus.variation_ids:type_name -> market.mass.ObjectId
	22, // 12: market.mass.ListingStockStatus.expected_in_stock_by:type_name -> google.protobuf.Timestamp
	5,  // 13: market.mass.PaymentDetails.payment_id:type_name -> market.mass.Hash
	8,  // 14: market.mass.PaymentDetails.total:type_name -> market.mass.Uint256
	7,  // 15: market.mass.PaymentDetails.listing_hashes:type_name -> market.mass.IPFSAddress
	3,  // 16: market.mass.PaymentDetails.shop_signature:type_name -> market.mass.Signature
	11, // 17: market.mass.PaymentDetails.shipping_region:type_name -> market.mass.ShippingRegion
	5,  // 18: market.mass.OrderTransaction.tx_hash:type_name -> market.mass.Hash
	5,  // 19: market.mass.OrderTransaction.block_hash:type_name -> market.mass.Hash
	2,  // 20: market.mass.OrderedItem.listing_id:type_name -> market.mass.ObjectId
	2,  // 21: market.mass.OrderedItem.variation_ids:type_name -> market.mass.ObjectId
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_base_types_proto_init() }
func file_base_types_proto_init() {
	if File_base_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthereumAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPFSAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uint256); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopCurrency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShippingRegion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPriceModifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlusMinus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingVariation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListingStockStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_types_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderedItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_base_types_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*OrderPriceModifier_Percentage)(nil),
		(*OrderPriceModifier_Absolute)(nil),
	}
	file_base_types_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*ListingStockStatus_InStock)(nil),
		(*ListingStockStatus_ExpectedInStockBy)(nil),
	}
	file_base_types_proto_msgTypes[17].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_types_proto_goTypes,
		DependencyIndexes: file_base_types_proto_depIdxs,
		EnumInfos:         file_base_types_proto_enumTypes,
		MessageInfos:      file_base_types_proto_msgTypes,
	}.Build()
	File_base_types_proto = out.File
	file_base_types_proto_rawDesc = nil
	file_base_types_proto_goTypes = nil
	file_base_types_proto_depIdxs = nil
}
