# SPDX-FileCopyrightText: 2024 Mass Labs
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: test

on: [push]

env:
  PGUSER: postgres
  PGPASSWORD: postgres
  PGHOST: localhost
  PGPORT: 5432

jobs:
  relay-tests:
    runs-on: [self-hosted, linux]
    # TODO: kludge until we figured out why pytest sometimes doesnt exit when tests fail
    timeout-minutes: 10

    permissions:
      contents: read

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      ipfs:
        image: cryptix/ipfs-offline:v1
        ports:
          - 5001:5001

      anvil:
        image: ghcr.io/foundry-rs/foundry:latest
        ports:
          - 8545:8545
        options: --entrypoint anvil
        env:
          ANVIL_IP_ADDR: 0.0.0.0

    steps:
      - uses: actions/checkout@v4
        with:
          path: relay

      # not needed on self-hosted but kept around if we want to use it on github-hosted
      #- name: Install Nix
      #  uses: DeterminateSystems/nix-installer-action@main
      #- uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          flake-lock-path: relay/flake.lock

      - name: Compile / smoke test relay
        run: nix build '.#relay'
        working-directory: relay

      # relay builds => run tests

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: git clone contracts
        uses: actions/checkout@v4
        with:
          repository: masslbs/contracts
          ref: ${{ steps.extract_branch.outputs.branch }}
          path: contracts

      - name: build ABIs and deploy market contracts
        run: nix develop -c deploy-market
        working-directory: contracts

      - name: git clone pystoretest
        uses: ./relay/.github/actions/checkout
        with:
          repository: masslbs/pystoretest
          ssh-key: ${{ secrets.SSH_CHECKOUT_PYSTORETEST }}
          path: pystoretest
          ref: ${{ steps.extract_branch.outputs.branch }} # same as PR

      - name: prepare env file for relay
        run: |
          cp .env.sample .env
          ../contracts/update_env.sh ../contracts/broadcast/deploy.s.sol/31337/run-latest.json | tee -a .env
          sed -i 's|PORT=4444|PORT=3434|' .env
          sed -i 's|localhost:4444|localhost:3434|' .env
          cat .env
        working-directory: relay

      - name: prepare env file for pystoretest
        run: |
          cp .env.sample .env
          sed -i 's|localhost:4444|localhost:3434|' .env
          cat .env
        working-directory: pystoretest

      - name: initdb and start relay
        run: |
          createdb massmarket-relay-test
          psql massmarket-relay-test < ./db/schema.sql
          export $(egrep -v '^#' .env | xargs)
          ./result/bin/relay server > relay.log &
        working-directory: relay

      - name: check services
        run: |
          set -e
          curl http://localhost:3434/health
          curl http://localhost:5001/api/v0/version -X POST
          curl http://localhost:8545/ -X POST -H 'content-type: application/json' --data-raw '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":0}'

      - name: Run tests
        run: nix develop -c pytest -x -k "not carts_happy"
        working-directory: pystoretest

      - name: Upload relay log on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: relay-log.txt
          path: relay/relay.log
